-- MySQL Script generated by MySQL Workbench
-- Mon May 31 17:53:56 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema coleta_dados
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema coleta_dados
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `coleta_dados` DEFAULT CHARACTER SET utf8 ;
USE `coleta_dados` ;

-- -----------------------------------------------------
-- Table `coleta_dados`.`animal_estimacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coleta_dados`.`animal_estimacao` (
  `cod_animal_estimacao` INT NOT NULL AUTO_INCREMENT,
  `animal` VARCHAR(45) NULL,
  PRIMARY KEY (`cod_animal_estimacao`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `coleta_dados`.`bebida`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coleta_dados`.`bebida` (
  `cod_bebida` INT NOT NULL AUTO_INCREMENT,
  `bebida` VARCHAR(45) NULL,
  PRIMARY KEY (`cod_bebida`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `coleta_dados`.`clima`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coleta_dados`.`clima` (
  `cod_clima` INT NOT NULL AUTO_INCREMENT,
  `clima` VARCHAR(45) NULL,
  PRIMARY KEY (`cod_clima`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `coleta_dados`.`hobbie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coleta_dados`.`hobbie` (
  `cod_hobbie` INT NOT NULL AUTO_INCREMENT,
  `hobbie` VARCHAR(45) NULL,
  PRIMARY KEY (`cod_hobbie`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `coleta_dados`.`pessoa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coleta_dados`.`pessoa` (
  `cod_pessoa` INT NOT NULL AUTO_INCREMENT,
  `genero` VARCHAR(45) NULL,
  `data_nascimento` VARCHAR(45) NULL,
  PRIMARY KEY (`cod_pessoa`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `coleta_dados`.`pesquisa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coleta_dados`.`pesquisa` (
  `cod_pesquisa` INT NOT NULL AUTO_INCREMENT,
  `data_pesquisa` DATE NULL,
  `cod_bebida` INT NOT NULL,
  `cod_animal_estimacao` INT NOT NULL,
  `cod_pessoa` INT NOT NULL,
  `cod_hobbie` INT NOT NULL,
  `cod_clima` INT NOT NULL,
  PRIMARY KEY (`cod_pesquisa`),
  INDEX `fk_pesquisa_bebida_idx` (`cod_bebida` ASC) VISIBLE,
  INDEX `fk_pesquisa_animal_estimacao1_idx` (`cod_animal_estimacao` ASC) VISIBLE,
  INDEX `fk_pesquisa_pessoa1_idx` (`cod_pessoa` ASC) VISIBLE,
  INDEX `fk_pesquisa_hobbie1_idx` (`cod_hobbie` ASC) VISIBLE,
  INDEX `fk_pesquisa_clima1_idx` (`cod_clima` ASC) VISIBLE,
  CONSTRAINT `fk_pesquisa_bebida`
    FOREIGN KEY (`cod_bebida`)
    REFERENCES `coleta_dados`.`bebida` (`cod_bebida`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pesquisa_animal_estimacao1`
    FOREIGN KEY (`cod_animal_estimacao`)
    REFERENCES `coleta_dados`.`animal_estimacao` (`cod_animal_estimacao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pesquisa_pessoa1`
    FOREIGN KEY (`cod_pessoa`)
    REFERENCES `coleta_dados`.`pessoa` (`cod_pessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pesquisa_hobbie1`
    FOREIGN KEY (`cod_hobbie`)
    REFERENCES `coleta_dados`.`hobbie` (`cod_hobbie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pesquisa_clima1`
    FOREIGN KEY (`cod_clima`)
    REFERENCES `coleta_dados`.`clima` (`cod_clima`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
